# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealioApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(max_length=25, unique=True)),
                ('name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='promotion',
            name='num_ratings',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotion',
            name='rating',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='num_deals',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='num_ratings',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rating',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='website_link',
            field=models.CharField(default='Example.com', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='restaurants',
            field=models.ManyToManyField(to='dealioApp.Restaurant'),
        ),
    ]
